"""Convert a NetPulse incident + baseline into an ARTEMIS rule config.

ARTEMIS expects YAML with three top-level keys: ``prefixes``,
``asns``, ``rules``. For a given labeled incident we declare the
victim AS as the legitimate origin for every prefix in the baseline,
so ARTEMIS' Type-0 / Type-N detectors have something to compare the
replayed updates against. Neighbors are left empty (ARTEMIS treats
that as "match any neighbor") because NetPulse's baseline doesn't
carry that field.

Usage:
    uv run python scripts/artemis_export_config.py \\
        data/incidents/youtube_2008.json \\
        docs/artemis/configs/youtube_2008.yaml
"""

from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path

from netpulse.storage.duckdb_store import BGPStore

REPO_ROOT = Path(__file__).resolve().parent.parent


def _resolve(incident_path: Path, rel: str | None) -> Path | None:
    if rel is None:
        return None
    return (incident_path.parent / rel).resolve()


def _emit_yaml(prefixes_by_origin: dict[int, list[str]], victim_asn: int) -> str:
    """Render an ARTEMIS config matching the prefix->origin map.

    The schema uses YAML anchors heavily. We emit one anchor per
    origin AS and one prefix-anchor per origin's prefix set.
    """
    lines: list[str] = []
    lines.append("# Auto-generated by scripts/artemis_export_config.py from a")
    lines.append("# NetPulse labeled-incident JSON. Do not edit by hand --")
    lines.append("# re-run the exporter when the incident or baseline changes.")
    lines.append("")
    lines.append(f"# Victim AS: {victim_asn}")
    lines.append("")

    # ---- prefixes -----
    lines.append("prefixes:")
    for origin, prefixes in sorted(prefixes_by_origin.items()):
        anchor = f"as{origin}_prefixes"
        lines.append(f"  {anchor}: &{anchor}")
        for p in sorted(prefixes):
            lines.append(f"  - {p}")
    lines.append("")

    # ---- asns -----
    lines.append("asns:")
    for origin in sorted(prefixes_by_origin):
        anchor = f"as{origin}"
        lines.append(f"  {anchor}: &{anchor}")
        lines.append(f"  - {origin}")
    lines.append("")

    # ---- rules -----
    lines.append("monitors:")
    lines.append("  bgpstreamhist: '/etc/artemis/'")
    lines.append("")
    lines.append("rules:")
    for origin in sorted(prefixes_by_origin):
        lines.append("- prefixes:")
        lines.append(f"  - *as{origin}_prefixes")
        lines.append("  origin_asns:")
        lines.append(f"  - *as{origin}")
        lines.append("  mitigation: manual")
    return "\n".join(lines) + "\n"


def export(incident_json_path: Path, out_yaml_path: Path) -> None:
    incident = json.loads(incident_json_path.read_text())

    baseline_rel = incident.get("baseline_path")
    if baseline_rel is None:
        raise SystemExit(
            f"incident {incident_json_path.name} has no baseline_path; "
            "ARTEMIS export requires a baseline."
        )
    baseline_path = _resolve(incident_json_path, baseline_rel)
    assert baseline_path is not None  # narrow for mypy
    if not baseline_path.exists():
        raise SystemExit(f"baseline file not found: {baseline_path}")

    # The baseline DuckDB carries (prefix, origin) rows; group them.
    prefixes_by_origin: dict[int, list[str]] = defaultdict(list)
    with BGPStore(baseline_path) as bs:
        rows = bs.query(
            "SELECT DISTINCT prefix, origin_as FROM bgp_records WHERE origin_as IS NOT NULL"
        )
    for prefix_raw, origin_raw in rows:
        prefixes_by_origin[int(origin_raw)].append(str(prefix_raw))

    if not prefixes_by_origin:
        raise SystemExit(f"baseline {baseline_path} carries no rows; nothing to declare to ARTEMIS")

    victim_asn = incident.get("victim_asn")
    if victim_asn is None:
        # Use the most-prefix-rich origin as a fallback identifier.
        victim_asn = max(prefixes_by_origin, key=lambda k: len(prefixes_by_origin[k]))

    yaml_text = _emit_yaml(prefixes_by_origin, int(victim_asn))
    out_yaml_path.parent.mkdir(parents=True, exist_ok=True)
    out_yaml_path.write_text(yaml_text)
    n_rules = len(prefixes_by_origin)
    n_prefixes = sum(len(v) for v in prefixes_by_origin.values())
    print(f"wrote {n_rules} ARTEMIS rule(s) covering {n_prefixes} prefix(es) -> {out_yaml_path}")


def main() -> None:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        sys.exit(2)
    export(Path(sys.argv[1]), Path(sys.argv[2]))


if __name__ == "__main__":
    main()
